/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 84
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 48
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_as = 3,
  sym_package_imp = 4,
  sym_package_lib = 5,
  anon_sym_POUNDextern = 6,
  anon_sym_GT_GT = 7,
  anon_sym_POUNDload = 8,
  anon_sym_COLON_COLON = 9,
  anon_sym_STAR = 10,
  anon_sym_COLON_TILDE = 11,
  anon_sym_COLON = 12,
  anon_sym_TILDE = 13,
  anon_sym_COLON_EQ = 14,
  anon_sym_EQ = 15,
  anon_sym_LPAREN = 16,
  anon_sym_COMMA = 17,
  anon_sym_RPAREN = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_raw = 21,
  anon_sym_str = 22,
  anon_sym_char = 23,
  anon_sym_func = 24,
  anon_sym_i8 = 25,
  anon_sym_i16 = 26,
  anon_sym_i32 = 27,
  anon_sym_i64 = 28,
  anon_sym_i128 = 29,
  anon_sym_u8 = 30,
  anon_sym_u16 = 31,
  anon_sym_u32 = 32,
  anon_sym_u64 = 33,
  anon_sym_u128 = 34,
  anon_sym_bool = 35,
  anon_sym_f16 = 36,
  anon_sym_f32 = 37,
  anon_sym_f64 = 38,
  anon_sym_f128 = 39,
  anon_sym_LBRACK_RBRACK = 40,
  anon_sym_LBRACK = 41,
  anon_sym_RBRACK = 42,
  anon_sym_LBRACK_LT = 43,
  anon_sym_GT_RBRACK = 44,
  sym_string_lit = 45,
  sym_ident = 46,
  sym_num = 47,
  sym_source_file = 48,
  sym__preproc = 49,
  sym_preproc_pkg = 50,
  sym_preproc_extern = 51,
  sym_preproc_load = 52,
  sym_resolve = 53,
  sym__expr = 54,
  sym__decl = 55,
  sym_func_decl = 56,
  sym_const_decl = 57,
  sym_mut_decl = 58,
  sym_decl_param_list = 59,
  sym_decl_param = 60,
  sym_param_list = 61,
  sym_scope = 62,
  sym__type = 63,
  sym_prim_type = 64,
  sym__array_type = 65,
  sym_slice_type = 66,
  sym_fixed_array_type = 67,
  sym_vector_type = 68,
  sym_func_call = 69,
  aux_sym_source_file_repeat1 = 70,
  aux_sym_resolve_repeat1 = 71,
  aux_sym_decl_param_list_repeat1 = 72,
  aux_sym_param_list_repeat1 = 73,
  aux_sym_scope_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_as] = "as",
  [sym_package_imp] = "package_imp",
  [sym_package_lib] = "package_lib",
  [anon_sym_POUNDextern] = "#extern",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_POUNDload] = "#load",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_STAR] = "*",
  [anon_sym_COLON_TILDE] = ":~",
  [anon_sym_COLON] = ":",
  [anon_sym_TILDE] = "~",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_raw] = "raw",
  [anon_sym_str] = "str",
  [anon_sym_char] = "char",
  [anon_sym_func] = "func",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_i64] = "i64",
  [anon_sym_i128] = "i128",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_u64] = "u64",
  [anon_sym_u128] = "u128",
  [anon_sym_bool] = "bool",
  [anon_sym_f16] = "f16",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_f128] = "f128",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACK_LT] = "[<",
  [anon_sym_GT_RBRACK] = ">]",
  [sym_string_lit] = "string_lit",
  [sym_ident] = "ident",
  [sym_num] = "num",
  [sym_source_file] = "source_file",
  [sym__preproc] = "_preproc",
  [sym_preproc_pkg] = "preproc_pkg",
  [sym_preproc_extern] = "preproc_extern",
  [sym_preproc_load] = "preproc_load",
  [sym_resolve] = "resolve",
  [sym__expr] = "_expr",
  [sym__decl] = "_decl",
  [sym_func_decl] = "func_decl",
  [sym_const_decl] = "const_decl",
  [sym_mut_decl] = "mut_decl",
  [sym_decl_param_list] = "decl_param_list",
  [sym_decl_param] = "decl_param",
  [sym_param_list] = "param_list",
  [sym_scope] = "scope",
  [sym__type] = "_type",
  [sym_prim_type] = "prim_type",
  [sym__array_type] = "_array_type",
  [sym_slice_type] = "slice_type",
  [sym_fixed_array_type] = "fixed_array_type",
  [sym_vector_type] = "vector_type",
  [sym_func_call] = "func_call",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_resolve_repeat1] = "resolve_repeat1",
  [aux_sym_decl_param_list_repeat1] = "decl_param_list_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
  [aux_sym_scope_repeat1] = "scope_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_as] = anon_sym_as,
  [sym_package_imp] = sym_package_imp,
  [sym_package_lib] = sym_package_lib,
  [anon_sym_POUNDextern] = anon_sym_POUNDextern,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_POUNDload] = anon_sym_POUNDload,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COLON_TILDE] = anon_sym_COLON_TILDE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_raw] = anon_sym_raw,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_i128] = anon_sym_i128,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_u128] = anon_sym_u128,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_f16] = anon_sym_f16,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_f128] = anon_sym_f128,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACK_LT] = anon_sym_LBRACK_LT,
  [anon_sym_GT_RBRACK] = anon_sym_GT_RBRACK,
  [sym_string_lit] = sym_string_lit,
  [sym_ident] = sym_ident,
  [sym_num] = sym_num,
  [sym_source_file] = sym_source_file,
  [sym__preproc] = sym__preproc,
  [sym_preproc_pkg] = sym_preproc_pkg,
  [sym_preproc_extern] = sym_preproc_extern,
  [sym_preproc_load] = sym_preproc_load,
  [sym_resolve] = sym_resolve,
  [sym__expr] = sym__expr,
  [sym__decl] = sym__decl,
  [sym_func_decl] = sym_func_decl,
  [sym_const_decl] = sym_const_decl,
  [sym_mut_decl] = sym_mut_decl,
  [sym_decl_param_list] = sym_decl_param_list,
  [sym_decl_param] = sym_decl_param,
  [sym_param_list] = sym_param_list,
  [sym_scope] = sym_scope,
  [sym__type] = sym__type,
  [sym_prim_type] = sym_prim_type,
  [sym__array_type] = sym__array_type,
  [sym_slice_type] = sym_slice_type,
  [sym_fixed_array_type] = sym_fixed_array_type,
  [sym_vector_type] = sym_vector_type,
  [sym_func_call] = sym_func_call,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_resolve_repeat1] = aux_sym_resolve_repeat1,
  [aux_sym_decl_param_list_repeat1] = aux_sym_decl_param_list_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
  [aux_sym_scope_repeat1] = aux_sym_scope_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [sym_package_imp] = {
    .visible = true,
    .named = true,
  },
  [sym_package_lib] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDextern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDload] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_raw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f128] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_string_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__preproc] = {
    .visible = false,
    .named = true,
  },
  [sym_preproc_pkg] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_load] = {
    .visible = true,
    .named = true,
  },
  [sym_resolve] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__decl] = {
    .visible = false,
    .named = true,
  },
  [sym_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_const_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_type] = {
    .visible = true,
    .named = true,
  },
  [sym__array_type] = {
    .visible = false,
    .named = true,
  },
  [sym_slice_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fixed_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_vector_type] = {
    .visible = true,
    .named = true,
  },
  [sym_func_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resolve_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decl_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '"', 1,
        '#', 8,
        '(', 37,
        ')', 39,
        '*', 31,
        ',', 38,
        ':', 33,
        '<', 21,
        '=', 36,
        '>', 23,
        '[', 62,
        ']', 63,
        'a', 92,
        'b', 89,
        'c', 85,
        'f', 67,
        'i', 68,
        'r', 82,
        's', 93,
        'u', 69,
        '{', 40,
        '}', 41,
        '~', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '(', 37,
        ':', 3,
        '>', 22,
        '[', 62,
        'b', 89,
        'c', 85,
        'f', 67,
        'i', 68,
        'r', 82,
        's', 93,
        'u', 69,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == ']') ADVANCE(65);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(6);
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 16:
      if (lookahead == 'x') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '"', 1,
        '#', 8,
        '(', 37,
        ')', 39,
        '*', 31,
        ',', 38,
        '=', 36,
        '>', 4,
        '{', 40,
        '}', 41,
        '~', 34,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '#') ADVANCE(8);
      if (lookahead == 'a') ADVANCE(92);
      if (lookahead == '}') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(28);
      if (lookahead == ']') ADVANCE(65);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_package_imp);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_package_lib);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POUNDextern);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUNDload);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON_TILDE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead == '~') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_raw);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_str);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_char);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_func);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_i8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_i16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_i32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_i64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_i128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_u8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_u16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_u32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_u64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_u128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_f16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_f32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_f64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_f128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '<') ADVANCE(64);
      if (lookahead == ']') ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LBRACK_LT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_GT_RBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_string_lit);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '1') ADVANCE(70);
      if (lookahead == '3') ADVANCE(71);
      if (lookahead == '6') ADVANCE(76);
      if (lookahead == 'u') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '1') ADVANCE(74);
      if (lookahead == '3') ADVANCE(72);
      if (lookahead == '6') ADVANCE(77);
      if (lookahead == '8') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '1') ADVANCE(75);
      if (lookahead == '3') ADVANCE(73);
      if (lookahead == '6') ADVANCE(78);
      if (lookahead == '8') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '2') ADVANCE(79);
      if (lookahead == '6') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '2') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '2') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '2') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '2') ADVANCE(80);
      if (lookahead == '6') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '2') ADVANCE(81);
      if (lookahead == '6') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '4') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '4') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '4') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '8') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '8') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '8') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'c') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'h') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'w') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 19},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 18},
  [32] = {.lex_state = 18},
  [33] = {.lex_state = 18},
  [34] = {.lex_state = 18},
  [35] = {.lex_state = 18},
  [36] = {.lex_state = 18},
  [37] = {.lex_state = 18},
  [38] = {.lex_state = 18},
  [39] = {.lex_state = 18},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 18},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 18},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 18},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 18},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 18},
  [68] = {.lex_state = 18},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 18},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 18},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 18},
  [82] = {.lex_state = 18},
  [83] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [sym_package_imp] = ACTIONS(1),
    [sym_package_lib] = ACTIONS(1),
    [anon_sym_POUNDextern] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_POUNDload] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COLON_TILDE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_raw] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_i128] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_u128] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_f16] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_f128] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK_LT] = ACTIONS(1),
    [anon_sym_GT_RBRACK] = ACTIONS(1),
    [sym_string_lit] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_num] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(75),
    [sym__preproc] = STATE(17),
    [sym_preproc_pkg] = STATE(17),
    [sym_preproc_extern] = STATE(17),
    [sym_preproc_load] = STATE(17),
    [sym__decl] = STATE(17),
    [sym_func_decl] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_package_imp] = ACTIONS(5),
    [sym_package_lib] = ACTIONS(5),
    [anon_sym_POUNDextern] = ACTIONS(7),
    [anon_sym_POUNDload] = ACTIONS(9),
    [sym_ident] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(21), 1,
      sym_ident,
    STATE(45), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [42] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(23), 1,
      sym_ident,
    STATE(77), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [84] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(25), 1,
      sym_ident,
    STATE(15), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [126] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(27), 1,
      sym_ident,
    STATE(11), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [168] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(29), 1,
      sym_ident,
    STATE(36), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [210] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(31), 1,
      sym_ident,
    STATE(59), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [252] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(33), 1,
      sym_ident,
    STATE(14), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [294] = 6,
    ACTIONS(15), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACK_LT,
    ACTIONS(35), 1,
      sym_ident,
    STATE(35), 6,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
      sym_vector_type,
    ACTIONS(13), 19,
      anon_sym_raw,
      anon_sym_str,
      anon_sym_char,
      anon_sym_func,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_i64,
      anon_sym_i128,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_u64,
      anon_sym_u128,
      anon_sym_bool,
      anon_sym_f16,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_f128,
  [336] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDextern,
    ACTIONS(9), 1,
      anon_sym_POUNDload,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(39), 1,
      sym_ident,
    STATE(69), 1,
      sym_resolve,
    ACTIONS(5), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(13), 8,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym_preproc_load,
      sym__decl,
      sym_func_decl,
      sym_func_call,
      aux_sym_scope_repeat1,
  [366] = 1,
    ACTIONS(41), 15,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_lit,
      sym_ident,
      sym_num,
  [384] = 1,
    ACTIONS(43), 15,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_lit,
      sym_ident,
      sym_num,
  [402] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDextern,
    ACTIONS(9), 1,
      anon_sym_POUNDload,
    ACTIONS(39), 1,
      sym_ident,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_resolve,
    ACTIONS(5), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(16), 8,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym_preproc_load,
      sym__decl,
      sym_func_decl,
      sym_func_call,
      aux_sym_scope_repeat1,
  [432] = 1,
    ACTIONS(47), 15,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_lit,
      sym_ident,
      sym_num,
  [450] = 1,
    ACTIONS(49), 15,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_lit,
      sym_ident,
      sym_num,
  [468] = 7,
    ACTIONS(54), 1,
      anon_sym_POUNDextern,
    ACTIONS(57), 1,
      anon_sym_POUNDload,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(62), 1,
      sym_ident,
    STATE(69), 1,
      sym_resolve,
    ACTIONS(51), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(16), 8,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym_preproc_load,
      sym__decl,
      sym_func_decl,
      sym_func_call,
      aux_sym_scope_repeat1,
  [498] = 6,
    ACTIONS(7), 1,
      anon_sym_POUNDextern,
    ACTIONS(9), 1,
      anon_sym_POUNDload,
    ACTIONS(11), 1,
      sym_ident,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(18), 7,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym_preproc_load,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [524] = 6,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 1,
      anon_sym_POUNDextern,
    ACTIONS(75), 1,
      anon_sym_POUNDload,
    ACTIONS(78), 1,
      sym_ident,
    ACTIONS(69), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(18), 7,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym_preproc_load,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [550] = 6,
    ACTIONS(9), 1,
      anon_sym_POUNDload,
    ACTIONS(85), 1,
      sym_ident,
    STATE(69), 1,
      sym_resolve,
    ACTIONS(81), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(83), 2,
      sym_string_lit,
      sym_num,
    STATE(65), 3,
      sym_preproc_load,
      sym__expr,
      sym_func_call,
  [573] = 1,
    ACTIONS(87), 9,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_ident,
  [585] = 1,
    ACTIONS(89), 9,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_ident,
  [597] = 1,
    ACTIONS(91), 9,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_GT_GT,
      anon_sym_POUNDload,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_ident,
  [609] = 1,
    ACTIONS(93), 9,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_ident,
  [621] = 1,
    ACTIONS(95), 9,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_GT_GT,
      anon_sym_POUNDload,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_ident,
  [633] = 5,
    ACTIONS(9), 1,
      anon_sym_POUNDload,
    ACTIONS(85), 1,
      sym_ident,
    STATE(69), 1,
      sym_resolve,
    ACTIONS(97), 2,
      sym_string_lit,
      sym_num,
    STATE(71), 3,
      sym_preproc_load,
      sym__expr,
      sym_func_call,
  [652] = 5,
    ACTIONS(9), 1,
      anon_sym_POUNDload,
    ACTIONS(85), 1,
      sym_ident,
    STATE(69), 1,
      sym_resolve,
    ACTIONS(99), 2,
      sym_string_lit,
      sym_num,
    STATE(49), 3,
      sym_preproc_load,
      sym__expr,
      sym_func_call,
  [671] = 2,
    ACTIONS(103), 1,
      anon_sym_GT_GT,
    ACTIONS(101), 7,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
      sym_ident,
  [684] = 1,
    ACTIONS(105), 8,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_ident,
  [695] = 3,
    ACTIONS(109), 1,
      anon_sym_as,
    ACTIONS(111), 1,
      sym_ident,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
  [710] = 7,
    ACTIONS(113), 1,
      anon_sym_COLON_COLON,
    ACTIONS(115), 1,
      anon_sym_COLON_TILDE,
    ACTIONS(117), 1,
      anon_sym_COLON,
    ACTIONS(119), 1,
      anon_sym_COLON_EQ,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    STATE(42), 1,
      aux_sym_resolve_repeat1,
    STATE(66), 2,
      sym_const_decl,
      sym_mut_decl,
  [733] = 1,
    ACTIONS(123), 7,
      anon_sym_POUNDload,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_string_lit,
      sym_ident,
      sym_num,
  [743] = 1,
    ACTIONS(125), 7,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
      sym_ident,
  [753] = 1,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
      sym_ident,
  [763] = 1,
    ACTIONS(129), 7,
      anon_sym_POUNDload,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_string_lit,
      sym_ident,
      sym_num,
  [773] = 1,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
      sym_ident,
  [783] = 2,
    ACTIONS(135), 1,
      anon_sym_EQ,
    ACTIONS(133), 6,
      anon_sym_POUNDload,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_string_lit,
      sym_ident,
      sym_num,
  [795] = 1,
    ACTIONS(137), 7,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
      sym_ident,
  [805] = 1,
    ACTIONS(139), 7,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
      sym_ident,
  [815] = 1,
    ACTIONS(141), 7,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_POUNDload,
      anon_sym_RBRACE,
      sym_ident,
  [825] = 4,
    ACTIONS(113), 1,
      anon_sym_COLON_COLON,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    STATE(42), 1,
      aux_sym_resolve_repeat1,
    ACTIONS(143), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [839] = 4,
    ACTIONS(115), 1,
      anon_sym_COLON_TILDE,
    ACTIONS(117), 1,
      anon_sym_COLON,
    ACTIONS(119), 1,
      anon_sym_COLON_EQ,
    STATE(66), 2,
      sym_const_decl,
      sym_mut_decl,
  [853] = 3,
    ACTIONS(147), 1,
      anon_sym_COLON_COLON,
    STATE(43), 1,
      aux_sym_resolve_repeat1,
    ACTIONS(145), 2,
      anon_sym_GT,
      anon_sym_LPAREN,
  [864] = 3,
    ACTIONS(151), 1,
      anon_sym_COLON_COLON,
    STATE(43), 1,
      aux_sym_resolve_repeat1,
    ACTIONS(149), 2,
      anon_sym_GT,
      anon_sym_LPAREN,
  [875] = 3,
    ACTIONS(115), 1,
      anon_sym_COLON_TILDE,
    ACTIONS(154), 1,
      anon_sym_COLON,
    STATE(64), 1,
      sym_const_decl,
  [885] = 3,
    ACTIONS(133), 1,
      anon_sym_LPAREN,
    ACTIONS(135), 1,
      anon_sym_EQ,
    ACTIONS(156), 1,
      anon_sym_TILDE,
  [895] = 1,
    ACTIONS(149), 3,
      anon_sym_GT,
      anon_sym_COLON_COLON,
      anon_sym_LPAREN,
  [901] = 3,
    ACTIONS(158), 1,
      anon_sym_GT_GT,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_scope,
  [911] = 3,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_param_list_repeat1,
  [921] = 3,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(48), 1,
      aux_sym_param_list_repeat1,
  [931] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_param_list_repeat1,
  [941] = 3,
    ACTIONS(119), 1,
      anon_sym_COLON_EQ,
    ACTIONS(173), 1,
      anon_sym_COLON,
    STATE(19), 1,
      sym_mut_decl,
  [951] = 3,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_decl_param_list_repeat1,
  [961] = 3,
    ACTIONS(179), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_decl_param_list_repeat1,
  [971] = 3,
    ACTIONS(113), 1,
      anon_sym_COLON_COLON,
    ACTIONS(121), 1,
      anon_sym_GT,
    STATE(42), 1,
      aux_sym_resolve_repeat1,
  [981] = 3,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_decl_param_list_repeat1,
  [991] = 1,
    ACTIONS(186), 2,
      anon_sym_GT,
      anon_sym_LPAREN,
  [996] = 2,
    ACTIONS(188), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_param_list,
  [1003] = 2,
    ACTIONS(190), 1,
      sym_ident,
    STATE(70), 1,
      sym_decl_param,
  [1010] = 2,
    ACTIONS(160), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_scope,
  [1017] = 1,
    ACTIONS(192), 2,
      anon_sym_STAR,
      sym_num,
  [1022] = 2,
    ACTIONS(194), 1,
      sym_ident,
    STATE(80), 1,
      sym_resolve,
  [1029] = 1,
    ACTIONS(196), 2,
      anon_sym_GT,
      anon_sym_LPAREN,
  [1034] = 2,
    ACTIONS(198), 1,
      anon_sym_STAR,
    ACTIONS(200), 1,
      sym_ident,
  [1041] = 2,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    STATE(27), 1,
      sym_decl_param_list,
  [1048] = 1,
    ACTIONS(204), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1053] = 2,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    STATE(47), 1,
      sym_decl_param_list,
  [1060] = 2,
    ACTIONS(190), 1,
      sym_ident,
    STATE(52), 1,
      sym_decl_param,
  [1067] = 2,
    ACTIONS(200), 1,
      sym_ident,
    ACTIONS(206), 1,
      anon_sym_STAR,
  [1074] = 2,
    ACTIONS(188), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_param_list,
  [1081] = 1,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1086] = 1,
    ACTIONS(171), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1091] = 1,
    ACTIONS(208), 1,
      anon_sym_LPAREN,
  [1095] = 1,
    ACTIONS(210), 1,
      anon_sym_RBRACK,
  [1099] = 1,
    ACTIONS(212), 1,
      sym_ident,
  [1103] = 1,
    ACTIONS(214), 1,
      ts_builtin_sym_end,
  [1107] = 1,
    ACTIONS(216), 1,
      anon_sym_GT_RBRACK,
  [1111] = 1,
    ACTIONS(156), 1,
      anon_sym_TILDE,
  [1115] = 1,
    ACTIONS(218), 1,
      anon_sym_LPAREN,
  [1119] = 1,
    ACTIONS(220), 1,
      sym_num,
  [1123] = 1,
    ACTIONS(222), 1,
      anon_sym_GT,
  [1127] = 1,
    ACTIONS(200), 1,
      sym_ident,
  [1131] = 1,
    ACTIONS(224), 1,
      sym_ident,
  [1135] = 1,
    ACTIONS(226), 1,
      anon_sym_LT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 210,
  [SMALL_STATE(8)] = 252,
  [SMALL_STATE(9)] = 294,
  [SMALL_STATE(10)] = 336,
  [SMALL_STATE(11)] = 366,
  [SMALL_STATE(12)] = 384,
  [SMALL_STATE(13)] = 402,
  [SMALL_STATE(14)] = 432,
  [SMALL_STATE(15)] = 450,
  [SMALL_STATE(16)] = 468,
  [SMALL_STATE(17)] = 498,
  [SMALL_STATE(18)] = 524,
  [SMALL_STATE(19)] = 550,
  [SMALL_STATE(20)] = 573,
  [SMALL_STATE(21)] = 585,
  [SMALL_STATE(22)] = 597,
  [SMALL_STATE(23)] = 609,
  [SMALL_STATE(24)] = 621,
  [SMALL_STATE(25)] = 633,
  [SMALL_STATE(26)] = 652,
  [SMALL_STATE(27)] = 671,
  [SMALL_STATE(28)] = 684,
  [SMALL_STATE(29)] = 695,
  [SMALL_STATE(30)] = 710,
  [SMALL_STATE(31)] = 733,
  [SMALL_STATE(32)] = 743,
  [SMALL_STATE(33)] = 753,
  [SMALL_STATE(34)] = 763,
  [SMALL_STATE(35)] = 773,
  [SMALL_STATE(36)] = 783,
  [SMALL_STATE(37)] = 795,
  [SMALL_STATE(38)] = 805,
  [SMALL_STATE(39)] = 815,
  [SMALL_STATE(40)] = 825,
  [SMALL_STATE(41)] = 839,
  [SMALL_STATE(42)] = 853,
  [SMALL_STATE(43)] = 864,
  [SMALL_STATE(44)] = 875,
  [SMALL_STATE(45)] = 885,
  [SMALL_STATE(46)] = 895,
  [SMALL_STATE(47)] = 901,
  [SMALL_STATE(48)] = 911,
  [SMALL_STATE(49)] = 921,
  [SMALL_STATE(50)] = 931,
  [SMALL_STATE(51)] = 941,
  [SMALL_STATE(52)] = 951,
  [SMALL_STATE(53)] = 961,
  [SMALL_STATE(54)] = 971,
  [SMALL_STATE(55)] = 981,
  [SMALL_STATE(56)] = 991,
  [SMALL_STATE(57)] = 996,
  [SMALL_STATE(58)] = 1003,
  [SMALL_STATE(59)] = 1010,
  [SMALL_STATE(60)] = 1017,
  [SMALL_STATE(61)] = 1022,
  [SMALL_STATE(62)] = 1029,
  [SMALL_STATE(63)] = 1034,
  [SMALL_STATE(64)] = 1041,
  [SMALL_STATE(65)] = 1048,
  [SMALL_STATE(66)] = 1053,
  [SMALL_STATE(67)] = 1060,
  [SMALL_STATE(68)] = 1067,
  [SMALL_STATE(69)] = 1074,
  [SMALL_STATE(70)] = 1081,
  [SMALL_STATE(71)] = 1086,
  [SMALL_STATE(72)] = 1091,
  [SMALL_STATE(73)] = 1095,
  [SMALL_STATE(74)] = 1099,
  [SMALL_STATE(75)] = 1103,
  [SMALL_STATE(76)] = 1107,
  [SMALL_STATE(77)] = 1111,
  [SMALL_STATE(78)] = 1115,
  [SMALL_STATE(79)] = 1119,
  [SMALL_STATE(80)] = 1123,
  [SMALL_STATE(81)] = 1127,
  [SMALL_STATE(82)] = 1131,
  [SMALL_STATE(83)] = 1135,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice_type, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_type, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fixed_array_type, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector_type, 4, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param_list, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_load, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param_list, 4, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_extern, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_pkg, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_pkg, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_extern, 6, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_pkg, 6, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 6, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_resolve_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resolve_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decl_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decl_param_list_repeat1, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_decl, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [214] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_decl, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caz(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "caz",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
