/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_as = 3,
  sym_package_imp = 4,
  sym_package_lib = 5,
  anon_sym_POUNDextern = 6,
  anon_sym_GT_GT = 7,
  anon_sym_COLON_COLON = 8,
  anon_sym_COLON_TILDE = 9,
  anon_sym_COLON = 10,
  anon_sym_TILDE = 11,
  anon_sym_COLON_EQ = 12,
  anon_sym_EQ = 13,
  anon_sym_LPAREN = 14,
  anon_sym_COMMA = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  anon_sym_raw = 19,
  anon_sym_str = 20,
  anon_sym_LBRACK_RBRACK = 21,
  anon_sym_LBRACK = 22,
  anon_sym_STAR = 23,
  anon_sym_RBRACK = 24,
  sym_string_lit = 25,
  sym_ident = 26,
  sym_num = 27,
  sym_source_file = 28,
  sym__preproc = 29,
  sym_preproc_pkg = 30,
  sym_preproc_extern = 31,
  sym_resolve = 32,
  sym__expr = 33,
  sym__decl = 34,
  sym_func_decl = 35,
  sym_const_decl = 36,
  sym_mut_decl = 37,
  sym_decl_param_list = 38,
  sym_decl_param = 39,
  sym_param_list = 40,
  sym_scope = 41,
  sym__type = 42,
  sym_prim_type = 43,
  sym__array_type = 44,
  sym_slice_type = 45,
  sym_fixed_array_type = 46,
  sym_func_call = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_resolve_repeat1 = 49,
  aux_sym_decl_param_list_repeat1 = 50,
  aux_sym_param_list_repeat1 = 51,
  aux_sym_scope_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_as] = "as",
  [sym_package_imp] = "package_imp",
  [sym_package_lib] = "package_lib",
  [anon_sym_POUNDextern] = "#extern",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_COLON_TILDE] = ":~",
  [anon_sym_COLON] = ":",
  [anon_sym_TILDE] = "~",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_raw] = "raw",
  [anon_sym_str] = "str",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_LBRACK] = "[",
  [anon_sym_STAR] = "*",
  [anon_sym_RBRACK] = "]",
  [sym_string_lit] = "string_lit",
  [sym_ident] = "ident",
  [sym_num] = "num",
  [sym_source_file] = "source_file",
  [sym__preproc] = "_preproc",
  [sym_preproc_pkg] = "preproc_pkg",
  [sym_preproc_extern] = "preproc_extern",
  [sym_resolve] = "resolve",
  [sym__expr] = "_expr",
  [sym__decl] = "_decl",
  [sym_func_decl] = "func_decl",
  [sym_const_decl] = "const_decl",
  [sym_mut_decl] = "mut_decl",
  [sym_decl_param_list] = "decl_param_list",
  [sym_decl_param] = "decl_param",
  [sym_param_list] = "param_list",
  [sym_scope] = "scope",
  [sym__type] = "_type",
  [sym_prim_type] = "prim_type",
  [sym__array_type] = "_array_type",
  [sym_slice_type] = "slice_type",
  [sym_fixed_array_type] = "fixed_array_type",
  [sym_func_call] = "func_call",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_resolve_repeat1] = "resolve_repeat1",
  [aux_sym_decl_param_list_repeat1] = "decl_param_list_repeat1",
  [aux_sym_param_list_repeat1] = "param_list_repeat1",
  [aux_sym_scope_repeat1] = "scope_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_as] = anon_sym_as,
  [sym_package_imp] = sym_package_imp,
  [sym_package_lib] = sym_package_lib,
  [anon_sym_POUNDextern] = anon_sym_POUNDextern,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_COLON_TILDE] = anon_sym_COLON_TILDE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_raw] = anon_sym_raw,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_string_lit] = sym_string_lit,
  [sym_ident] = sym_ident,
  [sym_num] = sym_num,
  [sym_source_file] = sym_source_file,
  [sym__preproc] = sym__preproc,
  [sym_preproc_pkg] = sym_preproc_pkg,
  [sym_preproc_extern] = sym_preproc_extern,
  [sym_resolve] = sym_resolve,
  [sym__expr] = sym__expr,
  [sym__decl] = sym__decl,
  [sym_func_decl] = sym_func_decl,
  [sym_const_decl] = sym_const_decl,
  [sym_mut_decl] = sym_mut_decl,
  [sym_decl_param_list] = sym_decl_param_list,
  [sym_decl_param] = sym_decl_param,
  [sym_param_list] = sym_param_list,
  [sym_scope] = sym_scope,
  [sym__type] = sym__type,
  [sym_prim_type] = sym_prim_type,
  [sym__array_type] = sym__array_type,
  [sym_slice_type] = sym_slice_type,
  [sym_fixed_array_type] = sym_fixed_array_type,
  [sym_func_call] = sym_func_call,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_resolve_repeat1] = aux_sym_resolve_repeat1,
  [aux_sym_decl_param_list_repeat1] = aux_sym_decl_param_list_repeat1,
  [aux_sym_param_list_repeat1] = aux_sym_param_list_repeat1,
  [aux_sym_scope_repeat1] = aux_sym_scope_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [sym_package_imp] = {
    .visible = true,
    .named = true,
  },
  [sym_package_lib] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDextern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_raw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_string_lit] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__preproc] = {
    .visible = false,
    .named = true,
  },
  [sym_preproc_pkg] = {
    .visible = true,
    .named = true,
  },
  [sym_preproc_extern] = {
    .visible = true,
    .named = true,
  },
  [sym_resolve] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__decl] = {
    .visible = false,
    .named = true,
  },
  [sym_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_const_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_param] = {
    .visible = true,
    .named = true,
  },
  [sym_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_type] = {
    .visible = true,
    .named = true,
  },
  [sym__array_type] = {
    .visible = false,
    .named = true,
  },
  [sym_slice_type] = {
    .visible = true,
    .named = true,
  },
  [sym_fixed_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_func_call] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resolve_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decl_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_scope_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 1,
        '#', 6,
        '(', 38,
        ')', 40,
        '*', 47,
        ',', 39,
        ':', 34,
        '<', 23,
        '=', 37,
        '>', 25,
        '[', 46,
        ']', 48,
        'a', 14,
        'r', 4,
        's', 15,
        '{', 41,
        '}', 42,
        '~', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(29);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'w') ADVANCE(43);
      END_STATE();
    case 18:
      if (lookahead == 'x') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 20:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 1,
        '#', 6,
        '(', 38,
        ')', 40,
        ',', 39,
        '=', 37,
        '>', 3,
        '{', 41,
        '}', 42,
        '~', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '(') ADVANCE(38);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == 'a') ADVANCE(50);
      if (lookahead == '}') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(31);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_package_imp);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_package_lib);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_POUNDextern);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COLON_TILDE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(32);
      if (lookahead == '=') ADVANCE(36);
      if (lookahead == '~') ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_raw);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == ']') ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_string_lit);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 20},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 20},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 20},
  [7] = {.lex_state = 20},
  [8] = {.lex_state = 20},
  [9] = {.lex_state = 20},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 20},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 20},
  [20] = {.lex_state = 20},
  [21] = {.lex_state = 21},
  [22] = {.lex_state = 20},
  [23] = {.lex_state = 20},
  [24] = {.lex_state = 20},
  [25] = {.lex_state = 20},
  [26] = {.lex_state = 20},
  [27] = {.lex_state = 20},
  [28] = {.lex_state = 20},
  [29] = {.lex_state = 20},
  [30] = {.lex_state = 20},
  [31] = {.lex_state = 20},
  [32] = {.lex_state = 20},
  [33] = {.lex_state = 20},
  [34] = {.lex_state = 20},
  [35] = {.lex_state = 20},
  [36] = {.lex_state = 20},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 21},
  [40] = {.lex_state = 21},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 20},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 21},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 20},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 20},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 20},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 20},
  [66] = {.lex_state = 20},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 20},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 21},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [sym_package_imp] = ACTIONS(1),
    [sym_package_lib] = ACTIONS(1),
    [anon_sym_POUNDextern] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_COLON_TILDE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_raw] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_string_lit] = ACTIONS(1),
    [sym_num] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(69),
    [sym__preproc] = STATE(9),
    [sym_preproc_pkg] = STATE(9),
    [sym_preproc_extern] = STATE(9),
    [sym__decl] = STATE(9),
    [sym_func_decl] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_package_imp] = ACTIONS(5),
    [sym_package_lib] = ACTIONS(5),
    [anon_sym_POUNDextern] = ACTIONS(7),
    [sym_ident] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(11), 14,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_lit,
      sym_ident,
      sym_num,
  [17] = 1,
    ACTIONS(13), 14,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_lit,
      sym_ident,
      sym_num,
  [34] = 1,
    ACTIONS(15), 14,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string_lit,
      sym_ident,
      sym_num,
  [51] = 6,
    ACTIONS(7), 1,
      anon_sym_POUNDextern,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      sym_ident,
    STATE(55), 1,
      sym_resolve,
    ACTIONS(5), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(7), 7,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym__decl,
      sym_func_decl,
      sym_func_call,
      aux_sym_scope_repeat1,
  [77] = 6,
    ACTIONS(7), 1,
      anon_sym_POUNDextern,
    ACTIONS(19), 1,
      sym_ident,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      sym_resolve,
    ACTIONS(5), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(5), 7,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym__decl,
      sym_func_decl,
      sym_func_call,
      aux_sym_scope_repeat1,
  [103] = 6,
    ACTIONS(26), 1,
      anon_sym_POUNDextern,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      sym_ident,
    STATE(55), 1,
      sym_resolve,
    ACTIONS(23), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(7), 7,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym__decl,
      sym_func_decl,
      sym_func_call,
      aux_sym_scope_repeat1,
  [129] = 5,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_POUNDextern,
    ACTIONS(42), 1,
      sym_ident,
    ACTIONS(36), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(8), 6,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [151] = 5,
    ACTIONS(7), 1,
      anon_sym_POUNDextern,
    ACTIONS(9), 1,
      sym_ident,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_package_imp,
      sym_package_lib,
    STATE(8), 6,
      sym__preproc,
      sym_preproc_pkg,
      sym_preproc_extern,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [173] = 4,
    ACTIONS(49), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(31), 5,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
  [191] = 4,
    ACTIONS(49), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(45), 5,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
  [209] = 4,
    ACTIONS(49), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(3), 5,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
  [227] = 4,
    ACTIONS(49), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(57), 5,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
  [245] = 4,
    ACTIONS(49), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(68), 5,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
  [263] = 4,
    ACTIONS(49), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(33), 5,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
  [281] = 4,
    ACTIONS(49), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(51), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(2), 5,
      sym__type,
      sym_prim_type,
      sym__array_type,
      sym_slice_type,
      sym_fixed_array_type,
  [299] = 5,
    ACTIONS(57), 1,
      sym_ident,
    STATE(55), 1,
      sym_resolve,
    ACTIONS(53), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(55), 2,
      sym_string_lit,
      sym_num,
    STATE(59), 2,
      sym__expr,
      sym_func_call,
  [318] = 7,
    ACTIONS(59), 1,
      anon_sym_COLON_COLON,
    ACTIONS(61), 1,
      anon_sym_COLON_TILDE,
    ACTIONS(63), 1,
      anon_sym_COLON,
    ACTIONS(65), 1,
      anon_sym_COLON_EQ,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    STATE(40), 1,
      aux_sym_resolve_repeat1,
    STATE(60), 2,
      sym_const_decl,
      sym_mut_decl,
  [341] = 1,
    ACTIONS(69), 8,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_GT_GT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_ident,
  [352] = 1,
    ACTIONS(71), 8,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_GT_GT,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_ident,
  [363] = 3,
    ACTIONS(75), 1,
      anon_sym_as,
    ACTIONS(77), 1,
      sym_ident,
    ACTIONS(73), 5,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
  [377] = 1,
    ACTIONS(79), 7,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_ident,
  [387] = 1,
    ACTIONS(81), 7,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_ident,
  [397] = 1,
    ACTIONS(83), 7,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_ident,
  [407] = 2,
    ACTIONS(87), 1,
      anon_sym_GT_GT,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
      sym_ident,
  [419] = 1,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
      sym_ident,
  [428] = 1,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
      sym_ident,
  [437] = 1,
    ACTIONS(93), 6,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_string_lit,
      sym_ident,
      sym_num,
  [446] = 1,
    ACTIONS(95), 6,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_string_lit,
      sym_ident,
      sym_num,
  [455] = 4,
    ACTIONS(57), 1,
      sym_ident,
    STATE(55), 1,
      sym_resolve,
    ACTIONS(97), 2,
      sym_string_lit,
      sym_num,
    STATE(48), 2,
      sym__expr,
      sym_func_call,
  [470] = 1,
    ACTIONS(99), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
      sym_ident,
  [479] = 1,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
      sym_ident,
  [488] = 2,
    ACTIONS(103), 1,
      anon_sym_EQ,
    ACTIONS(105), 5,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_string_lit,
      sym_ident,
      sym_num,
  [499] = 4,
    ACTIONS(57), 1,
      sym_ident,
    STATE(55), 1,
      sym_resolve,
    ACTIONS(107), 2,
      sym_string_lit,
      sym_num,
    STATE(62), 2,
      sym__expr,
      sym_func_call,
  [514] = 1,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
      sym_ident,
  [523] = 1,
    ACTIONS(111), 6,
      ts_builtin_sym_end,
      sym_package_imp,
      sym_package_lib,
      anon_sym_POUNDextern,
      anon_sym_RBRACE,
      sym_ident,
  [532] = 4,
    ACTIONS(61), 1,
      anon_sym_COLON_TILDE,
    ACTIONS(63), 1,
      anon_sym_COLON,
    ACTIONS(65), 1,
      anon_sym_COLON_EQ,
    STATE(60), 2,
      sym_const_decl,
      sym_mut_decl,
  [546] = 4,
    ACTIONS(59), 1,
      anon_sym_COLON_COLON,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
    STATE(40), 1,
      aux_sym_resolve_repeat1,
    ACTIONS(113), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [560] = 3,
    ACTIONS(117), 1,
      anon_sym_COLON_COLON,
    STATE(39), 1,
      aux_sym_resolve_repeat1,
    ACTIONS(115), 2,
      anon_sym_GT,
      anon_sym_LPAREN,
  [571] = 3,
    ACTIONS(59), 1,
      anon_sym_COLON_COLON,
    STATE(39), 1,
      aux_sym_resolve_repeat1,
    ACTIONS(120), 2,
      anon_sym_GT,
      anon_sym_LPAREN,
  [582] = 1,
    ACTIONS(115), 3,
      anon_sym_GT,
      anon_sym_COLON_COLON,
      anon_sym_LPAREN,
  [588] = 3,
    ACTIONS(61), 1,
      anon_sym_COLON_TILDE,
    ACTIONS(122), 1,
      anon_sym_COLON,
    STATE(58), 1,
      sym_const_decl,
  [598] = 3,
    ACTIONS(124), 1,
      anon_sym_GT_GT,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_scope,
  [608] = 3,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_decl_param_list_repeat1,
  [618] = 3,
    ACTIONS(103), 1,
      anon_sym_EQ,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 1,
      anon_sym_TILDE,
  [628] = 3,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_param_list_repeat1,
  [638] = 3,
    ACTIONS(59), 1,
      anon_sym_COLON_COLON,
    ACTIONS(67), 1,
      anon_sym_GT,
    STATE(40), 1,
      aux_sym_resolve_repeat1,
  [648] = 3,
    ACTIONS(134), 1,
      anon_sym_COMMA,
    ACTIONS(138), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_param_list_repeat1,
  [658] = 3,
    ACTIONS(140), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_decl_param_list_repeat1,
  [668] = 3,
    ACTIONS(128), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_RPAREN,
    STATE(44), 1,
      aux_sym_decl_param_list_repeat1,
  [678] = 3,
    ACTIONS(65), 1,
      anon_sym_COLON_EQ,
    ACTIONS(147), 1,
      anon_sym_COLON,
    STATE(17), 1,
      sym_mut_decl,
  [688] = 3,
    ACTIONS(149), 1,
      anon_sym_COMMA,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_param_list_repeat1,
  [698] = 2,
    ACTIONS(154), 1,
      sym_ident,
    STATE(61), 1,
      sym_decl_param,
  [705] = 1,
    ACTIONS(156), 2,
      anon_sym_STAR,
      sym_num,
  [710] = 2,
    ACTIONS(158), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_param_list,
  [717] = 2,
    ACTIONS(154), 1,
      sym_ident,
    STATE(50), 1,
      sym_decl_param,
  [724] = 2,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym_scope,
  [731] = 2,
    ACTIONS(160), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_decl_param_list,
  [738] = 1,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [743] = 2,
    ACTIONS(160), 1,
      anon_sym_LPAREN,
    STATE(43), 1,
      sym_decl_param_list,
  [750] = 1,
    ACTIONS(143), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [755] = 1,
    ACTIONS(152), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [760] = 2,
    ACTIONS(164), 1,
      sym_ident,
    STATE(73), 1,
      sym_resolve,
  [767] = 1,
    ACTIONS(166), 1,
      anon_sym_LPAREN,
  [771] = 1,
    ACTIONS(168), 1,
      sym_ident,
  [775] = 1,
    ACTIONS(170), 1,
      sym_ident,
  [779] = 1,
    ACTIONS(172), 1,
      anon_sym_LT,
  [783] = 1,
    ACTIONS(132), 1,
      anon_sym_TILDE,
  [787] = 1,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
  [791] = 1,
    ACTIONS(176), 1,
      anon_sym_LPAREN,
  [795] = 1,
    ACTIONS(178), 1,
      sym_ident,
  [799] = 1,
    ACTIONS(180), 1,
      anon_sym_RBRACK,
  [803] = 1,
    ACTIONS(182), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 51,
  [SMALL_STATE(6)] = 77,
  [SMALL_STATE(7)] = 103,
  [SMALL_STATE(8)] = 129,
  [SMALL_STATE(9)] = 151,
  [SMALL_STATE(10)] = 173,
  [SMALL_STATE(11)] = 191,
  [SMALL_STATE(12)] = 209,
  [SMALL_STATE(13)] = 227,
  [SMALL_STATE(14)] = 245,
  [SMALL_STATE(15)] = 263,
  [SMALL_STATE(16)] = 281,
  [SMALL_STATE(17)] = 299,
  [SMALL_STATE(18)] = 318,
  [SMALL_STATE(19)] = 341,
  [SMALL_STATE(20)] = 352,
  [SMALL_STATE(21)] = 363,
  [SMALL_STATE(22)] = 377,
  [SMALL_STATE(23)] = 387,
  [SMALL_STATE(24)] = 397,
  [SMALL_STATE(25)] = 407,
  [SMALL_STATE(26)] = 419,
  [SMALL_STATE(27)] = 428,
  [SMALL_STATE(28)] = 437,
  [SMALL_STATE(29)] = 446,
  [SMALL_STATE(30)] = 455,
  [SMALL_STATE(31)] = 470,
  [SMALL_STATE(32)] = 479,
  [SMALL_STATE(33)] = 488,
  [SMALL_STATE(34)] = 499,
  [SMALL_STATE(35)] = 514,
  [SMALL_STATE(36)] = 523,
  [SMALL_STATE(37)] = 532,
  [SMALL_STATE(38)] = 546,
  [SMALL_STATE(39)] = 560,
  [SMALL_STATE(40)] = 571,
  [SMALL_STATE(41)] = 582,
  [SMALL_STATE(42)] = 588,
  [SMALL_STATE(43)] = 598,
  [SMALL_STATE(44)] = 608,
  [SMALL_STATE(45)] = 618,
  [SMALL_STATE(46)] = 628,
  [SMALL_STATE(47)] = 638,
  [SMALL_STATE(48)] = 648,
  [SMALL_STATE(49)] = 658,
  [SMALL_STATE(50)] = 668,
  [SMALL_STATE(51)] = 678,
  [SMALL_STATE(52)] = 688,
  [SMALL_STATE(53)] = 698,
  [SMALL_STATE(54)] = 705,
  [SMALL_STATE(55)] = 710,
  [SMALL_STATE(56)] = 717,
  [SMALL_STATE(57)] = 724,
  [SMALL_STATE(58)] = 731,
  [SMALL_STATE(59)] = 738,
  [SMALL_STATE(60)] = 743,
  [SMALL_STATE(61)] = 750,
  [SMALL_STATE(62)] = 755,
  [SMALL_STATE(63)] = 760,
  [SMALL_STATE(64)] = 767,
  [SMALL_STATE(65)] = 771,
  [SMALL_STATE(66)] = 775,
  [SMALL_STATE(67)] = 779,
  [SMALL_STATE(68)] = 783,
  [SMALL_STATE(69)] = 787,
  [SMALL_STATE(70)] = 791,
  [SMALL_STATE(71)] = 795,
  [SMALL_STATE(72)] = 799,
  [SMALL_STATE(73)] = 803,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slice_type, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fixed_array_type, 4, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_type, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_scope_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param_list, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param_list, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_pkg, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_pkg, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_call, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_list, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_extern, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_extern, 6, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 6, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_pkg, 6, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_resolve_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resolve_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decl_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decl_param_list_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_param_list_repeat1, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_decl, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [174] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_decl, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caz(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "caz",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
