/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_POUNDimp = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_as = 4,
  anon_sym_COLON_COLON = 5,
  anon_sym_GT_GT = 6,
  anon_sym_COLON_TILDE = 7,
  anon_sym_COLON = 8,
  anon_sym_TILDE = 9,
  anon_sym_COLON_EQ = 10,
  anon_sym_EQ = 11,
  anon_sym_LPAREN = 12,
  anon_sym_COMMA = 13,
  anon_sym_RPAREN = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  anon_sym_raw = 17,
  anon_sym_str = 18,
  sym_ident = 19,
  sym_num = 20,
  sym_source_file = 21,
  sym__preproc = 22,
  sym_preproc_imp = 23,
  sym_resolve = 24,
  sym__expr = 25,
  sym__decl = 26,
  sym_func_decl = 27,
  sym_const_decl = 28,
  sym_mut_decl = 29,
  sym_decl_param_list = 30,
  sym_decl_param = 31,
  sym_scope = 32,
  sym__type = 33,
  sym_prim_type = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_resolve_repeat1 = 36,
  aux_sym_decl_param_list_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_POUNDimp] = "#imp",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_as] = "as",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_COLON_TILDE] = ":~",
  [anon_sym_COLON] = ":",
  [anon_sym_TILDE] = "~",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_raw] = "raw",
  [anon_sym_str] = "str",
  [sym_ident] = "ident",
  [sym_num] = "num",
  [sym_source_file] = "source_file",
  [sym__preproc] = "_preproc",
  [sym_preproc_imp] = "preproc_imp",
  [sym_resolve] = "resolve",
  [sym__expr] = "_expr",
  [sym__decl] = "_decl",
  [sym_func_decl] = "func_decl",
  [sym_const_decl] = "const_decl",
  [sym_mut_decl] = "mut_decl",
  [sym_decl_param_list] = "decl_param_list",
  [sym_decl_param] = "decl_param",
  [sym_scope] = "scope",
  [sym__type] = "_type",
  [sym_prim_type] = "prim_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_resolve_repeat1] = "resolve_repeat1",
  [aux_sym_decl_param_list_repeat1] = "decl_param_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_POUNDimp] = anon_sym_POUNDimp,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_COLON_TILDE] = anon_sym_COLON_TILDE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_raw] = anon_sym_raw,
  [anon_sym_str] = anon_sym_str,
  [sym_ident] = sym_ident,
  [sym_num] = sym_num,
  [sym_source_file] = sym_source_file,
  [sym__preproc] = sym__preproc,
  [sym_preproc_imp] = sym_preproc_imp,
  [sym_resolve] = sym_resolve,
  [sym__expr] = sym__expr,
  [sym__decl] = sym__decl,
  [sym_func_decl] = sym_func_decl,
  [sym_const_decl] = sym_const_decl,
  [sym_mut_decl] = sym_mut_decl,
  [sym_decl_param_list] = sym_decl_param_list,
  [sym_decl_param] = sym_decl_param,
  [sym_scope] = sym_scope,
  [sym__type] = sym__type,
  [sym_prim_type] = sym_prim_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_resolve_repeat1] = aux_sym_resolve_repeat1,
  [aux_sym_decl_param_list_repeat1] = aux_sym_decl_param_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_POUNDimp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_raw] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_num] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__preproc] = {
    .visible = false,
    .named = true,
  },
  [sym_preproc_imp] = {
    .visible = true,
    .named = true,
  },
  [sym_resolve] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym__decl] = {
    .visible = false,
    .named = true,
  },
  [sym_func_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_const_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_param_list] = {
    .visible = true,
    .named = true,
  },
  [sym_decl_param] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_prim_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_resolve_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_decl_param_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '#', 4,
        '(', 28,
        ')', 30,
        ',', 29,
        ':', 23,
        '<', 15,
        '=', 27,
        '>', 17,
        'a', 8,
        'r', 3,
        's', 9,
        '{', 31,
        '}', 32,
        '~', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(20);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'i') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'w') ADVANCE(33);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '#', 4,
        '(', 28,
        ')', 30,
        ',', 29,
        ':', 24,
        '=', 27,
        '>', 2,
        '{', 31,
        '}', 32,
        '~', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == '>') ADVANCE(16);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_POUNDimp);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_as);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COLON_TILDE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '~') ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(26);
      if (lookahead == '~') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_raw);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_num);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 12},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 12},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 12},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 11},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 11},
  [38] = {.lex_state = 12},
  [39] = {.lex_state = 11},
  [40] = {.lex_state = 12},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 11},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 11},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_POUNDimp] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_COLON_TILDE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_raw] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [sym_num] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(44),
    [sym__preproc] = STATE(4),
    [sym_preproc_imp] = STATE(4),
    [sym__expr] = STATE(4),
    [sym__decl] = STATE(4),
    [sym_func_decl] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_POUNDimp] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_num] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(13), 1,
      anon_sym_POUNDimp,
    ACTIONS(16), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_num,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(2), 6,
      sym__preproc,
      sym_preproc_imp,
      sym__expr,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [22] = 5,
    ACTIONS(24), 1,
      anon_sym_COLON_TILDE,
    ACTIONS(26), 1,
      anon_sym_COLON,
    ACTIONS(28), 1,
      anon_sym_COLON_EQ,
    STATE(30), 2,
      sym_const_decl,
      sym_mut_decl,
    ACTIONS(22), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_RBRACE,
      sym_ident,
      sym_num,
  [43] = 5,
    ACTIONS(5), 1,
      anon_sym_POUNDimp,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(30), 1,
      ts_builtin_sym_end,
    ACTIONS(32), 1,
      sym_num,
    STATE(2), 6,
      sym__preproc,
      sym_preproc_imp,
      sym__expr,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [64] = 5,
    ACTIONS(5), 1,
      anon_sym_POUNDimp,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(34), 1,
      anon_sym_RBRACE,
    ACTIONS(36), 1,
      sym_num,
    STATE(6), 6,
      sym__preproc,
      sym_preproc_imp,
      sym__expr,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [85] = 5,
    ACTIONS(5), 1,
      anon_sym_POUNDimp,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(32), 1,
      sym_num,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    STATE(2), 6,
      sym__preproc,
      sym_preproc_imp,
      sym__expr,
      sym__decl,
      sym_func_decl,
      aux_sym_source_file_repeat1,
  [106] = 1,
    ACTIONS(40), 8,
      anon_sym_TILDE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      sym_ident,
      sym_num,
  [117] = 3,
    ACTIONS(44), 1,
      anon_sym_as,
    ACTIONS(46), 1,
      sym_ident,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_RBRACE,
      sym_num,
  [130] = 1,
    ACTIONS(48), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_ident,
      sym_num,
  [138] = 1,
    ACTIONS(50), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_RBRACE,
      sym_ident,
      sym_num,
  [146] = 1,
    ACTIONS(52), 5,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_ident,
      sym_num,
  [154] = 1,
    ACTIONS(54), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_RBRACE,
      sym_ident,
      sym_num,
  [162] = 3,
    STATE(32), 1,
      sym__expr,
    ACTIONS(56), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(58), 2,
      sym_ident,
      sym_num,
  [174] = 2,
    ACTIONS(60), 1,
      anon_sym_EQ,
    ACTIONS(62), 4,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      sym_ident,
      sym_num,
  [184] = 1,
    ACTIONS(64), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_RBRACE,
      sym_ident,
      sym_num,
  [192] = 1,
    ACTIONS(66), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_RBRACE,
      sym_ident,
      sym_num,
  [200] = 1,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      anon_sym_POUNDimp,
      anon_sym_RBRACE,
      sym_ident,
      sym_num,
  [208] = 2,
    ACTIONS(70), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(36), 2,
      sym__type,
      sym_prim_type,
  [217] = 2,
    ACTIONS(70), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(14), 2,
      sym__type,
      sym_prim_type,
  [226] = 2,
    ACTIONS(70), 2,
      anon_sym_raw,
      anon_sym_str,
    STATE(23), 2,
      sym__type,
      sym_prim_type,
  [235] = 3,
    ACTIONS(72), 1,
      anon_sym_GT_GT,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_scope,
  [245] = 3,
    ACTIONS(76), 1,
      anon_sym_GT,
    ACTIONS(78), 1,
      anon_sym_COLON_COLON,
    STATE(26), 1,
      aux_sym_resolve_repeat1,
  [255] = 3,
    ACTIONS(60), 1,
      anon_sym_EQ,
    ACTIONS(62), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_TILDE,
  [265] = 3,
    ACTIONS(28), 1,
      anon_sym_COLON_EQ,
    ACTIONS(82), 1,
      anon_sym_COLON,
    STATE(13), 1,
      sym_mut_decl,
  [275] = 3,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      aux_sym_decl_param_list_repeat1,
  [285] = 3,
    ACTIONS(78), 1,
      anon_sym_COLON_COLON,
    ACTIONS(88), 1,
      anon_sym_GT,
    STATE(28), 1,
      aux_sym_resolve_repeat1,
  [295] = 3,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_decl_param_list_repeat1,
  [305] = 3,
    ACTIONS(92), 1,
      anon_sym_GT,
    ACTIONS(94), 1,
      anon_sym_COLON_COLON,
    STATE(28), 1,
      aux_sym_resolve_repeat1,
  [315] = 3,
    ACTIONS(97), 1,
      anon_sym_COMMA,
    ACTIONS(100), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_decl_param_list_repeat1,
  [325] = 2,
    ACTIONS(102), 1,
      anon_sym_LPAREN,
    STATE(21), 1,
      sym_decl_param_list,
  [332] = 1,
    ACTIONS(104), 2,
      anon_sym_GT_GT,
      anon_sym_LBRACE,
  [337] = 1,
    ACTIONS(106), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [342] = 2,
    ACTIONS(108), 1,
      sym_ident,
    STATE(35), 1,
      sym_decl_param,
  [349] = 1,
    ACTIONS(110), 2,
      anon_sym_GT_GT,
      anon_sym_LBRACE,
  [354] = 1,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [359] = 2,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_scope,
  [366] = 2,
    ACTIONS(112), 1,
      sym_ident,
    STATE(40), 1,
      sym_resolve,
  [373] = 1,
    ACTIONS(92), 2,
      anon_sym_GT,
      anon_sym_COLON_COLON,
  [378] = 2,
    ACTIONS(108), 1,
      sym_ident,
    STATE(25), 1,
      sym_decl_param,
  [385] = 1,
    ACTIONS(114), 1,
      anon_sym_GT,
  [389] = 1,
    ACTIONS(116), 1,
      anon_sym_LPAREN,
  [393] = 1,
    ACTIONS(118), 1,
      anon_sym_LT,
  [397] = 1,
    ACTIONS(120), 1,
      sym_ident,
  [401] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [405] = 1,
    ACTIONS(124), 1,
      anon_sym_LPAREN,
  [409] = 1,
    ACTIONS(126), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 43,
  [SMALL_STATE(5)] = 64,
  [SMALL_STATE(6)] = 85,
  [SMALL_STATE(7)] = 106,
  [SMALL_STATE(8)] = 117,
  [SMALL_STATE(9)] = 130,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 146,
  [SMALL_STATE(12)] = 154,
  [SMALL_STATE(13)] = 162,
  [SMALL_STATE(14)] = 174,
  [SMALL_STATE(15)] = 184,
  [SMALL_STATE(16)] = 192,
  [SMALL_STATE(17)] = 200,
  [SMALL_STATE(18)] = 208,
  [SMALL_STATE(19)] = 217,
  [SMALL_STATE(20)] = 226,
  [SMALL_STATE(21)] = 235,
  [SMALL_STATE(22)] = 245,
  [SMALL_STATE(23)] = 255,
  [SMALL_STATE(24)] = 265,
  [SMALL_STATE(25)] = 275,
  [SMALL_STATE(26)] = 285,
  [SMALL_STATE(27)] = 295,
  [SMALL_STATE(28)] = 305,
  [SMALL_STATE(29)] = 315,
  [SMALL_STATE(30)] = 325,
  [SMALL_STATE(31)] = 332,
  [SMALL_STATE(32)] = 337,
  [SMALL_STATE(33)] = 342,
  [SMALL_STATE(34)] = 349,
  [SMALL_STATE(35)] = 354,
  [SMALL_STATE(36)] = 359,
  [SMALL_STATE(37)] = 366,
  [SMALL_STATE(38)] = 373,
  [SMALL_STATE(39)] = 378,
  [SMALL_STATE(40)] = 385,
  [SMALL_STATE(41)] = 389,
  [SMALL_STATE(42)] = 393,
  [SMALL_STATE(43)] = 397,
  [SMALL_STATE(44)] = 401,
  [SMALL_STATE(45)] = 405,
  [SMALL_STATE(46)] = 409,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [26] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prim_type, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_imp, 4, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_preproc_imp, 4, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_decl, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preproc_imp, 6, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func_decl, 6, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_resolve, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_resolve_repeat1, 2, 0, 0),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_resolve_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_decl_param_list_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_decl_param_list_repeat1, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param_list, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl_param_list, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_decl, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [122] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_const_decl, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_caz(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "caz",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
